"""The scripted demo played by `vibe --provider fake`.

It exercises project inspection, file creation, terminal execution and the
final summary — the exact path a real LLM takes, minus the LLM.
"""

from __future__ import annotations

from .base import Message, ToolCall

DEMO_PY = '''\
"""Generated by Vibe (fake backend) to verify the agent pipeline works."""

import sys


def fib(n: int) -> int:
    """Iterative Fibonacci — no recursion limits, no surprises."""
    a, b = 0, 1
    for _ in range(n):
        a, b = b, a + b
    return a


if __name__ == "__main__":
    print("Hello from Vibe!")
    print("Python:", sys.version.split()[0])
    print("fib(10) =", fib(10))
'''

DEMO_STEPS = [
    Message(
        role="assistant",
        content="This is the scripted **fake** brain — it proves the whole pipeline "
                "(LLM -> agent loop -> tools -> safety -> executor) works end to end.\n\n"
                "Step 1: inspect the project layout.",
        tool_calls=[ToolCall(id="demo_0", name="project_summary", arguments={})],
    ),
    Message(
        role="assistant",
        content="Step 2: create a small, documented demo script.",
        tool_calls=[ToolCall(id="demo_1", name="write_file",
                             arguments={"path": "vibe_demo.py", "content": DEMO_PY})],
    ),
    Message(
        role="assistant",
        content="Step 3: run it to verify it actually works (never claim success without evidence).",
        tool_calls=[ToolCall(id="demo_2", name="run_command",
                             arguments={"command": "python vibe_demo.py"})],
    ),
    Message(
        role="assistant",
        content=(
            "**Demo complete — the agent pipeline works.** What just happened:\n\n"
            "1. `project_summary` inspected this folder (real tool, real output).\n"
            "2. `write_file` created `vibe_demo.py` (real file on disk).\n"
            "3. `run_command` executed it and returned the real exit code/output.\n"
            "4. Every step went through the safety layer and executor.\n\n"
            "The only scripted part was the *decisions* — with a real brain those "
            "come from a live model:\n\n"
            "    ollama pull qwen2.5-coder:7b\n"
            "    python vibe.py\n\n"
            "You can delete `vibe_demo.py` whenever you like."
        ),
        tool_calls=None,
    ),
]
